replicaCount: 1

image:
  repository: superbearcub/smashing-kubernetes
  pullPolicy: Always
  tag: "0.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3030

dashboards:
  path: /dashboards

jobs:
  path: /jobs

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

persistence:
  enabled: true
  storageClass: "local-storage"
  accessMode: ReadWriteOnce
  size: 1Gi
  existingClaim: ""


# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
